### ISSUE TITLE
IkoBB or TangoBB?

### ISSUE THREAD

**Issue by WebCrew** [IkoBB/IkoBB#20]
Hi **mates**,

first of all, thats a nice project, but also a **bit confusing** :)

At the TangoBB it sais in the README, that IkoBB stoped and You go back to TangoBB. Now I see, that at Tango the last GitHub development steps are 5-6 month ago, but IkoBB is only 4Days ago, so it seems IkoBB get active developed and TagoBB is dead?

- Which Forum should I use at the moment **IkoBB or TangoBB**?
- And **how to install IkoBB**, I cant find a install documentation or info :)

Kind regards, Andy

P.S.: keep up the good work and I wish You much success.

**Comment by N8boy** [comment]
Hi Andy,

It's a bit complicated. In the beginning there was only TangoBB. Someday the founder of **TangoBB** renamed the project to **Iko** and due to popular demand back to **TangoBB** again.

**IkoBB** was originally a fork of TangoBB, which came because of some internal team problems in TangoBB. So I decided to start a new project but with relation to TangoBB so I named the project according to Iko but with a BB behind it.

To your question which forum you should use now: 
To be honest: None. TangoBB looks dead for me and we rewrite at the moment everything so it will be later esier to modify it to your wishes. So there is no official release. Even the forum functions still not exist.

**But** as I said in the beginning we were a fork of TangoBB. So we have improved TangoBB already a bit but not much. So you can use this revision https://github.com/IkoBB/IkoBB/tree/core_change for setting up a forum. Later we will provide in the installer an import tool so you can easily transfer your users and posts to the new core.

**Comment by WebCrew** [comment]
Ok thanks for the info, now all becomes more clear to me. So far I`m not urgently in need of a forum so I´m glad to wait until the new version of IkoBB is ready to rock`n roll. IkoBB is on my watch list so I`ll not miss the updates ;)

Kind regards and good luck, Andy
